version: '3'
services:
  backend:
    image: node:18-alpine
    command: npm run start
    ports: 
      - 8000:8000
    working_dir: /backend
    volumes:
      - ./:/backend
      # - type: bind
      #   source: ./backend
      #   target: /backend

  db:
    image: postgres
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: gotyou
    ports:
      - 5432:5432

volumes:
  db-volume: 